title: Kehan Luo (Genghis)
description: Honors Maths & Data Science Undergraduate from NYUSH
site_title: 'Kehan's Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: kl4747@nyu.edu
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
